version: '3'
services: 
    # 各serviceのcontainer_nameを任意に変えてください
  web:
    image: nginx:1.15.6
    container_name: test-web
    ports: 
      - "8000:80"
    volumes: 
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs:/var/log/nginx
      - ./src:/var/www/html
    environment: 
      - TZ=${TZ}
    depends_on: 
      - app
  
  app:
    build: ./docker/php
    container_name: test-app
    volumes: 
      - ./src:/var/www/html
      - ./logs:/var/log/php
    working_dir: /var/www/html
    environment: 
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_DATABASE=${DB_NAME}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASS}
      - TZ=${TZ}
    depends_on: 
      - mysql
  
  mysql:
    image: mysql:5.7
    container_name: test-mysql
    ports: 
      - "3306:3306"
    volumes: 
      - ./db-store:/var/lib/mysql
      - ./logs:/var/log/mysql
    environment: 
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - TZ=${TZ}

volumes: 
  db-store:
    

      