version: '3'
services: 
    # .env 内のAPP_NAMEを設定してください
  web:
    container_name: ${APP_NAME}-web
    image: nginx:1.15.6
    ports: 
      - "8000:80"
    volumes: 
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs:/var/log/nginx
      - ./src:/var/www/html
    environment: 
      - TZ=${TZ}
    depends_on: 
      - app
  
  app:
    container_name: ${APP_NAME}-app
    build: ./docker/php
    volumes: 
      - ./src:/var/www/html
      - ./logs:/var/log/php
      #- vendor-volume:/var/www/html/${APP_NAME}/vendor
      #- storage-volume:/var/www/html/${APP_NAME}/storage
    working_dir: /var/www/html
    environment: 
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_DATABASE=${DB_NAME}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASS}
      - TZ=${TZ}
    depends_on: 
      - mysql
  
  mysql:
    container_name: ${APP_NAME}-mysql
    image: mysql:5.7
    ports: 
      - "3306:3306"
    volumes: 
      - ./db-store:/var/lib/mysql
      - ./logs:/var/log/mysql
    environment: 
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - TZ=${TZ}

volumes: 
  #vendor-volume:
  #storage-volume:
